function Location(){}

Location.FUERSTENPLATZ='FUERSTENPLATZ';
Location.FRIEDRICHSTADT='FRIEDRICHSTADT';
Location.HELMHOLTZSTRASSE='HELMHOLTZSTRASSE';
Location.MORSESTRASSE='MORSESTRASSE';

module.exports=Location;